name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: { persist-credentials: false }

      - uses: actions/setup-node@v1

      - uses: c-hive/gha-npm-cache@v1

      - run: npm install

      - uses: actions/cache@v2
        env: { cache-name: next-build }
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm run build
        env: { CI: true }

      # Copying files and artifacts via SSH
      - uses: appleboy/scp-action@master
        with:
          host: "v0.studio"
          username: ${{ secrets.SCP_ACTION_USER }}
          key: ${{ secrets.SCP_ACTION_USER_KEY }}
          rm: true
          source: "out/"
          target: "/var/www/html/v0-studio"
          strip_components: 1
