# .github/workflows/ssh_deploy.yml

name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: { persist-credentials: false }

      - uses: actions/setup-node@v1

      - run: npm install

      - run: npm run build
        env: { CI: true }

      # Copying files and artifacts via SSH
      - uses: appleboy/scp-action@master
        with:
          host: "v0.studio"
          username: ${{ secrets.SCP_ACTION_USER }}
          key: ${{ secrets.SCP_ACTION_USER_KEY }}
          rm: true
          source: "out/"
          target: "var/www/html/"
